### ISSUE TITLE
Add deviceready event

### ISSUE THREAD

**Issue by ttencate** [apache/cordova-electron#63] opened 2019-05-28 14:51 UTC
# Feature Request

## Motivation Behind Feature

[Cordova's documentation stresses](https://cordova.apache.org/docs/en/9.x/cordova/events/events.html#deviceready) that we need to wait for the `deviceready` event before doing anything:

> The deviceready event fires when Cordova is fully loaded. This event is essential to any application. It signals that Cordova's device APIs have loaded and are ready to access.

However, this [does not hold](https://stackoverflow.com/questions/43858331/dom-ready-event-inside-electron-how) for cordova-electron.

## Feature Description

Fire the `deviceready` event anyway, so the same code can be used across all Cordova platforms.

Or at least update the core documentation to mention that we _must not_ wait for `deviceready` on the Electron platform.

## Alternatives or Workarounds

Write platform-specific code to either wait for `deviceready`, or not.

**Comment by GedasGa** [comment] 2019-06-04 07:51
@ttencate could you show an example where it does not fire the `deviceready` event? I could not reproduce it. For me, using the base Cordova template with the Electron, I just modified the `index.js` file, to `console.log` a message.

```
var app = {
  initialize: function() {
    document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
  },

  onDeviceReady: function() {
    console.log('I was fired!')
  }
};

app.initialize();
```

 it triggered the `deviceready` event and printed the message to the `console`.

**Comment by ttencate** [comment] 2019-06-04 11:00
I decided to use Electron directly because Cordova was adding complexity for little value, so I didn't pursue this further. But I did add similar logging in my application and it didn't fire. Maybe it's because I turned off Node API access? Not sure whether that's enabled in the base template.

Anyway, if this is actually implemented, then this issue is probably a case of PEBKAC and can be closed. Sorry for the noise!

**Comment by erisu** [comment] 2019-06-11 04:51
Closing out the ticket as I also see the `deviceready` event being fired.

**Closed by erisu** 2019-06-11 04:51 UTC

**Comment by ttencate** [comment] 2019-06-13 15:41
For the record, I found the cause, and it was indeed my own fault. I was adding a `<script src="cordova.js"></script>` to the `<head>` at runtime from another script. Apparently that is either not allowed, or I was doing it wrong, but it confirms that the issue was clearly not with cordova-electron.
